name: Continuous integration

on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - 1.63.0 # MSRV
          - stable
          - nightly
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Install ${{ matrix.rust }} toolchain"
        # https://github.com/dtolnay/rust-toolchain?tab=readme-ov-file#inputs
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: "Use cache"
        uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: RUST_LOG=debug bash contrib/test.sh

  Format:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Install nightly toolchain"
        uses: dtolnay/rust-toolchain@nightly
      - name: "Use cache"
        uses: Swatinem/rust-cache@v2
      - run: rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu
      - name: "Run formatting check"
        run: cargo fmt --all -- --check

  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
        with:
          # checkout full tree
          fetch-depth: 0
      - name: "Install nightly toolchain"
        uses: dtolnay/rust-toolchain@nightly
      - name: "Use cache"
        uses: Swatinem/rust-cache@v2
      - name: "Install clippy"
        run: rustup component add clippy --toolchain nightly-x86_64-unknown-linux-gnu
      - name: "Run code linting on all commits"
        run: |
          for commit in $(git rev-list master..${{ github.sha }}); do
            git checkout $commit
            echo "checked out $commit"
            bash contrib/lint.sh
          done
      - name: "Run documentation linting"
        run: RUSTDOCFLAGS="-D warnings" cargo doc --no-deps --all-features --document-private-items

  Coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Install toolchain"
        # https://github.com/dtolnay/rust-toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: "Use cache"
        uses: Swatinem/rust-cache@v2
      - name: "Install cargo-llvm-cov"
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: "Generate code coverage for tests"
        run: bash contrib/coverage.sh
      - name: "Upload report to coveralls"
        uses: coverallsapp/github-action@v2
